FROM python:3.11
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    python3-dev \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /backend

COPY dependencies.txt .
RUN pip install --upgrade pip

RUN pip install  -r dependencies.txt 

COPY . .
EXPOSE 8000

CMD sh -c "python3 manage.py migrate && python3 server.py"